apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-counter-jenkins 
  labels:
    app: word-counter
spec:
  selector:
    matchLabels:
        app: word-counter
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: word-counter
    spec:
      containers:
        - name: word-counter
          image: 590184044177..dkr.ecr.us-east-2.amazonaws.com/word-counter:latest
          ports:
            - containerPort: 8085
              protocol: TCP
          imagePullPolicy: Always

